spring.application.name=Link

server.port=${PORT:8080}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

# ===============================
# LOCAL - PostgreSQL local
# Estos valores son solo fallback para desarrollo local
# ===============================
# spring.datasource.url=jdbc:postgresql://localhost:5432/safelink_db
# spring.datasource.username=postgres
# spring.datasource.password=postgre

# ===============================
# NEON / RENDER - Produccion
# Render debe enviar estos valores mediante Environment Variables
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/safelink_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgre}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:clave-local-de-desarrollo-safelink-32bytes-segura}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.security.user.name=disable
spring.security.user.password=disabled
