spring.application.name=Link
spring.datasource.url=jdbc:postgresql://localhost:5432/linkdb
spring.datasource.username=postgres
spring.datasource.password=casa1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true